project:
  type: book

lang: en

execute:
  freeze: auto
  echo: true
  warning: false

book:
  title: "ADK Setup"
  description: "Google Agent Development Kit (ADK) Setup"
  image: "/images/logo.png"
  favicon: "/images/logo.png"

  search:
    type: overlay

  page-footer:
    left: |
      © [Jan Kirenz](https://www.kirenz.com/), 2025

  chapters:


    - part: "Introduction"
      chapters:
        - index.qmd
        - preparation.qmd

    - part: "Install Python"
      chapters:
        - python-macos.qmd
        - python-windows.qmd

    - part: "Build Your Workspace"
      chapters:
        - venv-and-pip.qmd
        - adk-install.qmd
        - first-agent.qmd
        - jupyter.qmd

    - part: troubleshooting/index.qmd
      chapters:
        - troubleshooting/common-errors.qmd

    - part: appendix/glossary.qmd
      chapters:
        - appendix/faq.qmd
        - appendix/references.qmd

number-sections: true 

format:
  html:
    toc: true
    theme: cosmo
    css: theme.scss
    code-copy: true
    highlight-style: github-dark
    code-overflow: wrap
    author-meta: "Jan Kirenz"
    callout-appearance: simple
    include-in-header:
      text: |
        <style>
        .cmd-explain {
          font-weight: 600;
          margin-top: 1rem;
        }
        </style>
